
from __future__ import annotations

# ─── MOCK USERS (Candidate) ─────────────────────────────────────────────
MOCK_USERS: list[dict] = [
    {
        "id": 1,
        "full_name": "Nguyễn Văn An",
        "email": "an.nguyen@email.com",
        "phone": "0901234567",
        "created_at": "15/03/2026",
        "applications_count": 5,
        "is_active": True,
        "role": "candidate",
    },
    {
        "id": 2,
        "full_name": "Trần Thị Bình",
        "email": "binh.tran@email.com",
        "phone": "0902345678",
        "created_at": "20/03/2026",
        "applications_count": 3,
        "is_active": True,
        "role": "candidate",
    },
    {
        "id": 3,
        "full_name": "Lê Hoàng Cường",
        "email": "cuong.le@email.com",
        "phone": "0903456789",
        "created_at": "22/03/2026",
        "applications_count": 8,
        "is_active": True,
        "role": "candidate",
    },
    {
        "id": 4,
        "full_name": "Phạm Minh Đức",
        "email": "duc.pham@email.com",
        "phone": "0904567890",
        "created_at": "25/03/2026",
        "applications_count": 2,
        "is_active": False,
        "role": "candidate",
    },
    {
        "id": 5,
        "full_name": "Võ Thị Em",
        "email": "em.vo@email.com",
        "phone": "0905678901",
        "created_at": "01/04/2026",
        "applications_count": 4,
        "is_active": True,
        "role": "candidate",
    },
]

# ─── MOCK HR ─────────────────────────────────────────────────────────────
MOCK_HR_LIST: list[dict] = [
    {
        "id": 1,
        "company_name": "TechCorp Vietnam",
        "email": "hr@techcorp.vn",
        "phone": "0241234567",
        "created_at": "10/02/2026",
        "jobs_count": 12,
        "is_active": True,
    },
    {
        "id": 2,
        "company_name": "StartUp Innovation",
        "email": "recruit@startup.vn",
        "phone": "0282345678",
        "created_at": "15/02/2026",
        "jobs_count": 8,
        "is_active": True,
    },
    {
        "id": 3,
        "company_name": "Design Studio",
        "email": "jobs@designstudio.vn",
        "phone": "0236789012",
        "created_at": "20/02/2026",
        "jobs_count": 5,
        "is_active": True,
    },
    {
        "id": 4,
        "company_name": "Digital Agency",
        "email": "hr@digital.vn",
        "phone": "0243456789",
        "created_at": "25/02/2026",
        "jobs_count": 3,
        "is_active": False,
    },
    {
        "id": 5,
        "company_name": "Cloud Solutions",
        "email": "recruit@cloud.vn",
        "phone": "0285678901",
        "created_at": "01/03/2026",
        "jobs_count": 9,
        "is_active": True,
    },
]

# ─── MOCK JOBS (Admin view) ─────────────────────────────────────────────
MOCK_ADMIN_JOBS: list[dict] = [
    {
        "id": 1,
        "title": "Senior Frontend Developer",
        "company_name": "TechCorp Vietnam",
        "location": "Hà Nội",
        "salary_text": "2000 - 3000 USD",
        "job_type": "Full-time",
        "applicants_count": 23,
        "created_at": "10/04/2026",
        "status": "published",
    },
    {
        "id": 2,
        "title": "Backend Developer (Node.js)",
        "company_name": "StartUp Innovation",
        "location": "Hồ Chí Minh",
        "salary_text": "1500 - 2500 USD",
        "job_type": "Full-time",
        "applicants_count": 18,
        "created_at": "08/04/2026",
        "status": "published",
    },
    {
        "id": 3,
        "title": "UI/UX Designer",
        "company_name": "Design Studio",
        "location": "Đà Nẵng",
        "salary_text": "1000 - 1800 USD",
        "job_type": "Remote",
        "applicants_count": 31,
        "created_at": "05/04/2026",
        "status": "published",
    },
    {
        "id": 4,
        "title": "Full Stack Developer",
        "company_name": "Digital Agency",
        "location": "Hà Nội",
        "salary_text": "2500 - 3500 USD",
        "job_type": "Full-time",
        "applicants_count": 15,
        "created_at": "03/04/2026",
        "status": "rejected",
    },
    {
        "id": 5,
        "title": "DevOps Engineer",
        "company_name": "Cloud Solutions",
        "location": "Hồ Chí Minh",
        "salary_text": "2200 - 3200 USD",
        "job_type": "Full-time",
        "applicants_count": 9,
        "created_at": "01/04/2026",
        "status": "draft",
    },
]

# ─── MOCK: Danh sách job công khai (cho Candidate Dashboard) ─────────────
MOCK_JOBS: list[dict] = [
    {
        "id": 101,
        "title": "Lập trình viên Python (Backend)",
        "description": "Phát triển API FastAPI, tích hợp PostgreSQL, viết test tự động. "
        "Môi trường làm việc linh hoạt, đào tạo nội bộ.",
        "company_name": "TechViet Solutions",
        "location": "Hà Nội (hybrid)",
        "job_type": "Full-time",
        "salary_text": "18–28 triệu",
    },
    {
        "id": 102,
        "title": "Frontend React / TypeScript",
        "description": "Xây dựng giao diện web hiện đại, làm việc với design system và CI/CD.",
        "company_name": "Bright Apps",
        "location": "TP.HCM",
        "job_type": "Full-time",
        "salary_text": "20–35 triệu",
    },
    {
        "id": 103,
        "title": "Thực tập sinh Data Analyst",
        "description": "Phân tích dữ liệu kinh doanh, SQL, báo cáo dashboard cho ban lãnh đạo.",
        "company_name": "Retail Analytics Co.",
        "location": "Đà Nẵng",
        "job_type": "Internship",
        "salary_text": "5 triệu + phụ cấp",
    },
    {
        "id": 104,
        "title": "DevOps Engineer",
        "description": "Kubernetes, Docker, pipeline GitHub Actions, giám sát hạ tầng cloud.",
        "company_name": "CloudScale VN",
        "location": "Remote",
        "job_type": "Full-time",
        "salary_text": "25–40 triệu",
    },
]

MOCK_CVS: list[dict] = [
    {"id": 1, "original_name": "CV_NguyenVanA.pdf"},
    {"id": 2, "original_name": "Portfolio_EN.docx"},
]

MOCK_HR_DASHBOARD: dict = {
    "cards": {"jobs": 12, "candidates": 48, "views": 3200, "response_rate": 42},
    "labels": ["Tuần 1", "Tuần 2", "Tuần 3", "Tuần 4"],
    "values": [18, 24, 31, 27],
}

MOCK_HR_ACTIVITY: list[dict] = [
    {
        "dot_color": "#6366f1",
        "text": "Nguyễn Văn A ứng tuyển cho Senior Developer",
        "time": "1 giờ trước",
        "bold": True,
    },
    {
        "dot_color": "#94a3b8",
        "text": "Lịch phỏng vấn với Trần Thị B",
        "time": "10:00 AM mai",
        "bold": False,
    },
    {
        "dot_color": "#6366f1",
        "text": "Hồ sơ của Lê Thanh C đã được cập nhật",
        "time": "2 giờ trước",
        "bold": True,
    },
    {
        "dot_color": "#10b981",
        "text": "Tin đăng 'Frontend Developer' được duyệt",
        "time": "Hôm qua 17:30",
        "bold": False,
    },
    {
        "dot_color": "#f59e0b",
        "text": "Phạm Minh D đã xem hồ sơ của bạn",
        "time": "3 giờ trước",
        "bold": False,
    },
]

MOCK_HR_JOBS: list[dict] = [
    {
        "id": 501,
        "title": "Senior Backend Engineer",
        "department": "Kỹ thuật & Công nghệ",
        "created_at": "15/10/2023",
        "applicants_count": 24,
        "status": "published",
    },
    {
        "id": 502,
        "title": "Product Designer (UI/UX)",
        "department": "Thiết kế",
        "created_at": "14/10/2023",
        "applicants_count": 18,
        "status": "draft",
    },
    {
        "id": 503,
        "title": "Marketing Manager",
        "department": "Marketing",
        "created_at": "10/10/2023",
        "applicants_count": 0,
        "status": "published",
    },
    {
        "id": 504,
        "title": "Content Writer",
        "department": "Marketing",
        "created_at": "05/10/2023",
        "applicants_count": 32,
        "status": "closed",
    },
    {
        "id": 505,
        "title": "Data Analyst",
        "department": "Kinh doanh",
        "created_at": "28/09/2023",
        "applicants_count": 11,
        "status": "published",
    },
    {
        "id": 506,
        "title": "DevOps Engineer",
        "department": "Kỹ thuật & Công nghệ",
        "created_at": "20/09/2023",
        "applicants_count": 7,
        "status": "pending_approval",
    },
    {
        "id": 507,
        "title": "UX Researcher",
        "department": "Thiết kế",
        "created_at": "15/09/2023",
        "applicants_count": 14,
        "status": "published",
    },
    {
        "id": 508,
        "title": "Backend Engineer (Python)",
        "department": "Kỹ thuật & Công nghệ",
        "created_at": "10/09/2023",
        "applicants_count": 22,
        "status": "draft",
    },
    {
        "id": 509,
        "title": "Sales Manager",
        "department": "Kinh doanh",
        "created_at": "05/09/2023",
        "applicants_count": 0,
        "status": "pending_approval",
    },
]

MOCK_HR_APPLICATIONS: list[dict] = [
    {
        "application_id": 9001,
        "candidate_name": "Trần Thị Bình",
        "candidate_email": "binh.tran@email.com",
        "job_title": "Senior Backend Engineer",
        "status": "pending",
        "cv_name": "TranThiB_CV.pdf",
        "applied_at": "15/04/2026",
    },
    {
        "application_id": 9002,
        "candidate_name": "Lê Văn Cường",
        "candidate_email": "cuong.le@email.com",
        "job_title": "Product Designer (UI/UX)",
        "status": "reviewed",
        "cv_name": "LeVanC_Portfolio.pdf",
        "applied_at": "14/04/2026",
    },
    {
        "application_id": 9003,
        "candidate_name": "Nguyễn Văn An",
        "candidate_email": "an.nguyen@email.com",
        "job_title": "Data Analyst",
        "status": "approved",
        "cv_name": "NguyenVanA_CV.pdf",
        "applied_at": "13/04/2026",
    },
    {
        "application_id": 9004,
        "candidate_name": "Phạm Minh Đức",
        "candidate_email": "duc.pham@email.com",
        "job_title": "DevOps Engineer",
        "status": "rejected",
        "cv_name": "PhamMinhD_CV.pdf",
        "applied_at": "12/04/2026",
    },
    {
        "application_id": 9005,
        "candidate_name": "Võ Thị Em",
        "candidate_email": "em.vo@email.com",
        "job_title": "Marketing Manager",
        "status": "pending",
        "cv_name": "VoThiE_Resume.pdf",
        "applied_at": "11/04/2026",
    },
    {
        "application_id": 9006,
        "candidate_name": "Hoàng Anh Tuấn",
        "candidate_email": "tuan.hoang@email.com",
        "job_title": "Senior Backend Engineer",
        "status": "reviewed",
        "cv_name": "HoangAnhT_CV.pdf",
        "applied_at": "10/04/2026",
    },
    {
        "application_id": 9007,
        "candidate_name": "Đặng Thị Lan",
        "candidate_email": "lan.dang@email.com",
        "job_title": "Content Writer",
        "status": "approved",
        "cv_name": "DangThiL_Portfolio.pdf",
        "applied_at": "09/04/2026",
    },
    {
        "application_id": 9008,
        "candidate_name": "Trần Văn Hùng",
        "candidate_email": "hung.tran@email.com",
        "job_title": "Senior Backend Engineer",
        "status": "pending",
        "cv_name": "TranVanH_CV.pdf",
        "applied_at": "08/04/2026",
    },
    {
        "application_id": 9009,
        "candidate_name": "Nguyễn Thị Mai",
        "candidate_email": "mai.nguyen@email.com",
        "job_title": "Product Designer (UI/UX)",
        "status": "approved",
        "cv_name": "NguyenThiM_CV.pdf",
        "applied_at": "07/04/2026",
    },
    {
        "application_id": 9010,
        "candidate_name": "Lê Quốc Bảo",
        "candidate_email": "bao.le@email.com",
        "job_title": "Data Analyst",
        "status": "reviewed",
        "cv_name": "LeQuocB_CV.pdf",
        "applied_at": "06/04/2026",
    },
    {
        "application_id": 9011,
        "candidate_name": "Phùng Thị Hoa",
        "candidate_email": "hoa.phung@email.com",
        "job_title": "Marketing Manager",
        "status": "rejected",
        "cv_name": "PhungThiH_CV.pdf",
        "applied_at": "05/04/2026",
    },
    {
        "application_id": 9012,
        "candidate_name": "Bùi Minh Khoa",
        "candidate_email": "khoa.bui@email.com",
        "job_title": "DevOps Engineer",
        "status": "pending",
        "cv_name": "BuiMinhK_CV.pdf",
        "applied_at": "04/04/2026",
    },
    {
        "application_id": 9013,
        "candidate_name": "Vũ Thị Ngọc",
        "candidate_email": "ngoc.vu@email.com",
        "job_title": "Content Writer",
        "status": "reviewed",
        "cv_name": "VuThiN_CV.pdf",
        "applied_at": "03/04/2026",
    },
    {
        "application_id": 9014,
        "candidate_name": "Đinh Công Sơn",
        "candidate_email": "son.dinh@email.com",
        "job_title": "Senior Backend Engineer",
        "status": "approved",
        "cv_name": "DinhCongS_CV.pdf",
        "applied_at": "02/04/2026",
    },
    {
        "application_id": 9015,
        "candidate_name": "Cao Thị Yến",
        "candidate_email": "yen.cao@email.com",
        "job_title": "Data Analyst",
        "status": "pending",
        "cv_name": "CaoThiY_CV.pdf",
        "applied_at": "01/04/2026",
    },
]

MOCK_ADMIN_DASHBOARD: dict = {
    "cards": {"users": 1240, "hr": 86, "jobs": 320, "activity_today": 45},
    "labels": ["T2", "T3", "T4", "T5", "T6", "T7", "CN"],
    "values": [12, 19, 15, 22, 18, 8, 5],
}

MOCK_ADMIN_USERS: list[dict] = [
    {"id": 1, "email": "admin@jobhub.local", "role": "admin"},
    {"id": 2, "email": "hr@demo.local", "role": "hr"},
    {"id": 3, "email": "user@demo.local", "role": "candidate"},
]

MOCK_PENDING_HR: list[dict] = [
    {"id": 10, "email": "pending.hr@company.com"},
]

MOCK_PENDING_JOBS: list[dict] = [
    {"id": 701, "title": "Marketing Executive — chờ duyệt"},
]
